### ISSUE TITLE
Fix eln nightly builds

### ISSUE THREAD

**Issue by inknos** [rpm-software-management/dnf5#1030]
ELN builds currently fail for dnf5 in copr dnf-nightly.

https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf-nightly/monitor/

We can provide some rebuilds for the needed packages, or ask some of the packages to build for ELN too.

```
No matching package to install: 'pkgconfig(fmt)'
No matching package to install: 'pkgconfig(sdbus-c++) >= 0.8.1'
No matching package to install: 'pkgconfig(smartcols)'
No matching package to install: 'pkgconfig(zck) >= 0.9.11'
Package rpm-build-4.19.0-2.eln132.x86_64 is already installed.
No matching package to install: 'python3dist(breathe)'
No matching package to install: 'toml11-static'
Not all dependencies satisfied
Error: Some packages could not be found.
```

Snipped taken from [here](https://download.copr.fedorainfracloud.org/results/rpmsoftwaremanagement/dnf-nightly/fedora-eln-x86_64/06671932-dnf5/builder-live.log.gz)

Related to https://github.com/rpm-software-management/dnf/issues/2009

**Comment by ppisar** [comment]
I checked _pkgconfig(fmt)_: In Fedora it comes from _fmt_ component. Latest build in _eln-build_ tag is fmt-10.1.1-1.eln132. And that provides _pkgconfig(fmt)_ in fmt-devel binary package. So the package is built.

Is it in a compose COPR uses?

~~~~
$ koji list-history --build fmt-10.1.1-1.eln132
Wed Nov 15 16:03:43 2023 fmt-10.1.1-1.eln132 tagged into eln-build-side-77756 by distrobuildsync-eln/jenkins-continuous-infra.apps.ci.centos.org
Wed Nov 15 16:33:44 2023 fmt-10.1.1-1.eln132 untagged from eln-build-side-77756 by distrobuildsync-eln/jenkins-continuous-infra.apps.ci.centos.org
Wed Nov 15 16:33:49 2023 fmt-10.1.1-1.eln132 tagged into eln-updates-candidate by distrobuildsync-eln/jenkins-continuous-infra.apps.ci.centos.org
Wed Nov 15 16:34:20 2023 fmt-10.1.1-1.eln132 tagged into eln-signing-pending by bodhi
Wed Nov 15 16:34:53 2023 fmt-10.1.1-1.eln132 untagged from eln-signing-pending by autopen
Wed Nov 15 16:34:53 2023 fmt-10.1.1-1.eln132 tagged into eln-updates-testing-pending by autopen
Wed Nov 15 16:36:38 2023 fmt-10.1.1-1.eln132 untagged from eln-updates-testing-pending by bodhi
Wed Nov 15 16:36:38 2023 fmt-10.1.1-1.eln132 untagged from eln-updates-candidate by bodhi
Wed Nov 15 16:36:59 2023 fmt-10.1.1-1.eln132 tagged into eln by bodhi [still active]
~~~~

It is tagged into "eln" since 2023-11-15.

Is it in a compose?

~~~~
# dnf5 --disablerepo=\* --enablerepo=eln\* repoquery --qf '%{repoid} %{name}-%{version}-%{release}\n' 'fmt-devel'
Updating and loading repositories:
Repositories loaded.
eln-build fmt-devel-10.1.1-1.eln132
# dnf5 --disablerepo=\* --enablerepo=eln\* repoquery --qf '%{repoid} %{name}-%{version}-%{release}\n' 'fmt'
Updating and loading repositories:
Repositories loaded.
eln-build fmt-10.1.1-1.eln132
eln-extras fmt-10.1.1-1.eln132
eln-extras-source fmt-10.1.1-1.eln132
~~~~

It is, but not everywhere. ELN probably wants to keep fmt-devel in build root only (eln-build), and pull "fmt" into eln-baseos only if dnf5 appears there. I guess dnf5 is excluded from RHEL 10, hence it is not in ELN. The repository definitions are packaged in Fedora fedora-repos-eln package. "eln-build" is my own repo pointing to Koji.

Does COPR use eln-build repository for building COPR packages? From <https://download.copr.fedorainfracloud.org/results/rpmsoftwaremanagement/dnf-nightly/fedora-eln-x86_64/06671932-dnf5/builder-live.log.gz>:

~~~~
This system is not registered with an entitlement server. You can use subscription-manager to register.

Copr repository                                 1.3 MB/s |  83 kB     00:00    
Fedora - ELN BaseOS - Developmental packages fo 5.6 MB/s | 1.6 MB     00:00    
Fedora - ELN AppStream - Developmental packages  14 MB/s | 6.3 MB     00:00    
Fedora - ELN CodeReady Linux Builders - Build p 5.0 MB/s | 4.4 MB     00:00    
Fedora - ELN Extras - Developmental packages fo 3.8 MB/s | 2.5 MB     00:00    
Dependencies resolved.
~~~~

It does not.

So either we can add eln-build repository <https://kojipkgs.fedoraproject.org/repos/eln-build/latest/$basearch> to our COPR project definition, or we need to rebuild the missing packages.

**Comment by inknos** [comment]
> So either we can add eln-build repository https://kojipkgs.fedoraproject.org/repos/eln-build/latest/$basearch to our COPR project definition, or we need to rebuild the missing packages.

my preference is to add all copr repositories to the chroots that require a missing dependency and build only what we really need

**Comment by inknos** [comment]
I enabled the repo only for eln and looks like the builds are passing now. thanks @ppisar

**Comment by inknos** [comment]
I enabled the repo for eln. All builds are healty now
