### ISSUE TITLE
libdnf5 doesn't pick highest NEVRA when a package is available from 2 arches

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#1111]
Anaconda's nightly tests are hitting an odd problem roblem -- packages with different arches are trying to be installed at the same time: https://github.com/rhinstaller/kickstart-tests/actions/runs/7263835386/job/19790019961

```
Problem: cannot install both anaconda-install-img-deps-40.12-1.20231205144801720625.master.3.gd66b9912c5.fc40.noarch and anaconda-install-img-deps-40.15-1.20231219045442936819.master.0.gc6e2e850b8.fc40.x86_64
    - conflicting requests
```

The copr repo at https://download.copr.fedorainfracloud.org/results/%40rhinstaller/Anaconda/fedora-rawhide-x86_64/ seems to have grouped all the different builds together, and it ends up that it has the `anaconda-install-img-deps` package in there as both a noarch and as x86_64. With libdnf5 it is returning BOTH of these, despite the x86_64 version being higher, and then trying to install both and getting a conflict.

This seems to be a filtering issue because with dnf4 I only see it return the higher version:

```pkgnames = [<hawkey.Package object id 137195, anaconda-install-img-deps-40.15-1.20231219045442936819.master.0.gc6e2e850b8.fc40.x86_64, lorax-repo-2>]```

**Comment by j-mracek** [comment]
I guess that the problem is not in query but in way how they are used.
Expectation from the latest filter.

For each `name` and `architecture` keep all package objects with the latest version. It means for each architecture it keeps  the latest version including `noarch`, `x86_64`, `i686` or even non compatible architecture for your system `s390`, ... .

I believe that you have a different expectation therefore you are not satisfy with the query results. May I ask you for clarification of expected results when multiple architecture and multiple version are present in available repositories?
For `x86_64` systems there are following packages available: 

anaconda-1-1.noarch
anaconda-3-3.noarch from repo B
anaconda-3-3.noarch from repo A
anaconda-3-3.noarch from repo A
anaconda-2.2.x86_64
anaconda-2.3.i686
anaconda-3-4.s390

**Comment by bcl** [comment]
I would expect the same behavior as dnf4, which seems to be the highest NEVR irrespective of arch.

**Comment by j-mracek** [comment]
I am suggesting to add a new method to our API
