### ISSUE TITLE
libdnf5 get_comps explanation

### ISSUE THREAD

**Issue by anaselli** [rpm-software-management/dnf5#1319]
It seems [get_comps documentation](https://dnf5.readthedocs.io/en/latest/api/python/libdnf5_base_base.html#libdnf5.base.Base.get_comps) is missing.

I tried the following python code 

```
import libdnf5
base = libdnf5.base.Base()
base.load_config()
base.setup()
comps_gr = base.get_comps()
print(comps_gr)
```
without any success of getting comps groups, it returns 
`<libdnf5.comps.CompsWeakPtr; proxy of <Swig Object of type 'libdnf5::WeakPtr< libdnf5::comps::Comps,false > *' at 0x7f6071179470> >`
And honestly i don't know how to use it.

Following test files i tried also the following code:

```
import libdnf5
base = libdnf5.base.Base()
base.load_config()
config = base.get_config()
types_config = config.get_optional_metadata_types_option()
types_config.add(libdnf5.conf.Option.Priority_RUNTIME, (libdnf5.conf.METADATA_TYPE_COMPS))
base.setup()
query = libdnf5.comps.GroupQuery(base)
groups = [grp.get_groupid() for grp in query]
print(groups)
```
with or without the following lines:
```
types_config = config.get_optional_metadata_types_option()
types_config.add(libdnf5.conf.Option.Priority_RUNTIME, (libdnf5.conf.METADATA_TYPE_COMPS))
```
I got an empty list anyway.

Any help? What am I doing wrong?

**Comment by kontura** [comment]
The problem is that the `get_comps()` and `libdnf5::comps::Comps`, `libdnf5::comps::EnvironmentSack` and `libdnf5::comps::GroupSack` are not doing anything. It is an issue in the API and they will be removed.

Your approach with the `libdnf5.comps.GroupQuery` is correct, you just need to load the repositories.
This is working for me:
```python
import libdnf5
base = libdnf5.base.Base()
base.setup()

repo_sack = base.get_repo_sack()
repo_sack.create_repos_from_system_configuration()
repo_sack.update_and_load_enabled_repos(True)

query = libdnf5.comps.GroupQuery(base)
groups = [grp.get_groupid() for grp in query]
print(groups)
```

The  `libdnf5.conf.METADATA_TYPE_COMPS` in `optional_metadata_types_option` is set by default but since you want to work with the comps metadata it is perhaps good to make sure.
