### ISSUE TITLE
Missing space before error message in string

### ISSUE THREAD

**Issue by HarmfulBreeze** [rpm-software-management/dnf5#1480]
There should probably be a space between the colon and the error message: https://github.com/rpm-software-management/dnf5/blob/4b62aef58cb04b134e08c9bde2384ef0c0c1d55c/libdnf5/base/log_event.cpp#L249

**Comment by ppisar** [comment]
The missing space is good because the second argument starts with a new-line as you can see 8 lines above. 

Though I agree that it's not obvious from from the message catalog. We should either document, or change the code. Provided the code suffers from other localization problem (missing plural forms, nonlilized item separators) , I'd rather change the code.
