### ISSUE TITLE
dnf5-5.2.1.0 said rawhide repo metadata download is >1TiB with speeds over 5GiB/s

### ISSUE THREAD

**Issue by juhp** [rpm-software-management/dnf5#1500]
Of course it is not, but this seems a real regression in the latest release

![Screenshot from 2024-05-18 00-13-37](https://github.com/rpm-software-management/dnf5/assets/82731/cb5a8612-9cf0-422f-a42f-156adf8e84f3)

```
Updating and loading repositories:
 Fedora - Rawhide - Developmental packages for the next Fedora release                      100% |  29.2 KiB/s |  37.8 KiB |  00m01s
 Fedora - Rawhide - Developmental packages for the next Fedora release 100% [==================] |   2.8 GiB/s |   1.1 TiB | -00m00s Fedora - Rawhide - Developmental packages for the next Fedora release                      100% |   1.5 GiB/s |   1.1 TiB |  12m50s
>>> Librepo error: Librepo was interrupted by a signalFailed to download metadata (metalink: "https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=x86_64") for repository "rawhide"
 Librepo error: Librepo was interrupted by a signal
^C
```

I am using:
dnf5-5.2.1.0-1.fc41.x86_64
librepo-1.17.1-1.fc41.x86_64

Finally the 3rd time it worked normally
Not sure if this could have been caused by some broken mirror, but never seen this before

**Comment by juhp** [comment]
I probably can't reproduce this easily, so maybe can be closed?

**Comment by ppisar** [comment]
Thanks for the report. Indeed capturing a repository which triggers this would be great.

The total amount of data to download are both stored in repomd.xml on the mirror and sent in HTTP response. I don't know which one DNF prints to the terminal. Ideally librepo should abort the transfer if HTTP response indicated a different size. Also there could be an inteteger overlflow through out the DNF stack.

The download speed is always questionable because it's as inaccurate as short is the transfer.
