### ISSUE TITLE
If local path to package is set in arguments, do not refresh repos  unless there are unmet dependencies

### ISSUE THREAD

**Issue by solomoncyj** [rpm-software-management/dnf5#1570]
![image](https://github.com/rpm-software-management/dnf5/assets/74647769/c77f426e-a147-49ac-af36-0cbe68ec7772)
dnf can save time if it does not refresh the repos unneccesarily

**Comment by ppisar** [comment]
DNF does not refresh repositories. It downloads additional data from repositories, so called filelists. These additional data contains a mapping from files to packages the packages provides. You can verify it by repeating the command.

DNF downloads the filelists if an absolute file path is given for an installation (`dnf5 install /foo`). The reason is that DNF does not know whether a user wants to install a missing file, or a local RPM package.

A workaround for you is to change the absolute path a relative one (`dnf5 install ../foo`), or to a file:// URL (`dnf5 install file:///foo`).

However, I agree that the current behavior is obtrusive and DNF should prefer an installation of a local RPM package over a package which owns the file path.

Why DNF behaves as it behaves, I don't know. Maybe because otherwise it would be impossible to install a package by a file if that file already existed locally. That's would be quite strange use case because that file would be overwritten in turn, but as much strange the use case, it's still a valid use case.

**Comment by ppisar** [comment]
I would like other DNF5 developers to express their opinion.

**Comment by j-mracek** [comment]
I think we should improve detection mechanism. We should use the same algorithm like arg parser uses for detection rpms.

**Comment by jan-kolarik** [comment]
I agree, the file argument detection should be improved.

**Comment by ppisar** [comment]
I believe your problem was addresses in commit fd9c4cd17dce941aa7870844727bf3119dc81a9b.

Your idea of not refreshing repositories if all dependencies are met cannot be implemented: DNF be design does not retry dependency resolution, neither do any speculative resolution. It simply considers all data it has available and reports a success or a failure. (This is how DNF implemented e.g. not downloading file lists.) Another clashing feature is refreshing repositories when they have expired.

**Comment by solomoncyj** [comment]
> I believe your problem was addresses in commit [fd9c4cd](https://github.com/rpm-software-management/dnf5/commit/fd9c4cd17dce941aa7870844727bf3119dc81a9b).
> 
> Your idea of not refreshing repositories if all dependencies are met cannot be implemented: DNF be design does not retry dependency resolution, neither do any speculative resolution. It simply considers all data it has available and reports a success or a failure. (This is how DNF implemented e.g. not downloading file lists.) Another clashing feature is refreshing repositories when they have expired.

so say, in the event there is no internet connection, will it still install? or must I fall back to rpm?

**Comment by ppisar** [comment]
There is a --cacheonly option that inhibits any refreshes.
