### ISSUE TITLE
Fix docs for commands accepting specs

### ISSUE THREAD

**Issue by kontura** [rpm-software-management/dnf5#1602]
`install`, `upgrade` and `remove` commands are documented to accept only packages (`<package-spec>`) but they work also with comps.

**Comment by ppisar** [comment]
It's not only documentation. "dnf install --help" also reads:

~~~~
Arguments:                                     
  specs                                        List of package specs to install
~~~~

I think `package-spec` identifier should be kept reserved for packages and would should change documentation to `package-spec|group-spec` where appropriate. Otherwise, the grammar would accept `@group > 2` which is obviously unwanted.
