### ISSUE TITLE
Package removal by provides does not work

### ISSUE THREAD

**Issue by Dapid** [rpm-software-management/dnf5#1937]
I am sorry, I don't know the right terminology. By alias I mean `dnf install python312` redirects to `python3.12`, but `dnf remove python312` doesn't.

```
dnf install python312
Updating and loading repositories:
 Fedora 41 - x86_64 - Updates                                                                                                                        100% |  21.0 KiB/s |  26.7 KiB |  00m01s
 Fedora 41 - x86_64 - Updates                                                                                                                        100% |   1.5 MiB/s |   1.9 MiB |  00m01s
Repositories loaded.
Package                                                         Arch           Version                                                          Repository                               Size
Installing:
 python3.12                                                     x86_64         3.12.7-1.fc41                                                    fedora                               31.5 KiB
Installing dependencies:
 python3.12-libs                                                x86_64         3.12.7-1.fc41                                                    fedora                               41.3 MiB
Installing weak dependencies:
 python3.12-tkinter                                             x86_64         3.12.7-1.fc41                                                    fedora                                2.2 MiB

Transaction Summary:
 Installing:         3 packages

Total size of inbound packages is 10 MiB. Need to download 10 MiB.
After this operation, 44 MiB extra will be used (install 44 MiB, remove 0 B).
Is this ok [y/N]:
```
On remove:
```
# dnf remove python312
No packages to remove for argument: python312

Nothing to do.
# dnf remove python3.12
Package                                                         Arch           Version                                                          Repository                               Size
Removing:
 python3.12                                                     x86_64         3.12.7-1.fc41                                                    fedora                               31.5 KiB
Removing unused dependencies:
 python3.12-libs                                                x86_64         3.12.7-1.fc41                                                    fedora                               41.3 MiB
 python3.12-tkinter                                             x86_64         3.12.7-1.fc41                                                    fedora                                2.2 MiB

Transaction Summary:
 Removing:           3 packages

Is this ok [y/N]:
```

By the way, great job on the new version! I like how fast it is!

**Comment by ppisar** [comment]
That's a feature documented in dnf5-changes-from-dnf4(7):

> Command no longer removes packages according to provides, but only based on  NEVRA  or file provide match.

It was changed because a repeated removal by a provide was not idempotent if there were installed packages with the provide and an additional package with its name equal to the provide. Then dnf only removed the package, but on subsequent call removed packages providing the identifier. Alternative solution was removing all of them, but then users would loose a possibility only uninstall a package with the name.

**Comment by Dapid** [comment]
I see.

Would suggest the correct package be an option? Or at least indicate if I request the wrong package.

**Comment by ppisar** [comment]
DNF cannot know whether it was a typo, an RPM provide (your case), or an intended request (e.g. to make sure the package is not installed). While DNF could lookup in the provides, it would have a performance impact on the other cases.

In addition, package removal, which does not need up-to-date repository metadata now, would suddenly start downloading the metadata. We could probably limit the search for provides among installed packages. That would prevent from downloading the metadata. Nevertheless it would still had some cost. DNF in general avoids expensive operation which are not always needed.

Rather than that I could imagine adding a new subcommand or an option to remove all provides. E.g. "dnf remove --with-provides IDENTIFIER". But currently that would be a very low priority request for enhancement.

**Comment by sanjayankur31** [comment]
While I completely understand the reasoning here, it's still unintuitive that `dnf install` will work with provides but that `dnf remove` would not. Would the same issues not also apply to the `install` command, including the performance impact of downloading/looking up provides?

**Comment by ppisar** [comment]
I agree with you that it's not handy and I'd like to see a possibility to uninstall by a provide. But it cannot be done with "remove" command if want to support the edge case I described above. We either add a new optoin, new command, or come up with a new syntax how to specifically address a provide, a package name, or both.

The performance question differs in that "dnf install" performs one lookup before installation, while "dnf remove" would perform two lookups. One before the removal, another after the (failed) removal.
