### ISSUE TITLE
unknown type concept  /usr/include/libdnf5/common/exception.hpp

### ISSUE THREAD

**Issue by acidburnmonkey** [rpm-software-management/dnf5#1954]
unknown type concept error on this line 
```
concept AllowedErrorArgTypes =
    std::is_arithmetic_v<T> || std::is_base_of_v<std::string, T> || std::is_null_pointer_v<T> ||
    std::is_same_v<const void *, T> || std::is_same_v<void *, T>;```

**Comment by ppisar** [comment]
Did you mean a compiler error like:

~~~~
In file included from test.cpp:1:
/usr/include/libdnf5/common/exception.hpp:138:1: error: ‘concept’ does not name a type; did you mean ‘const’?
  138 | concept AllowedErrorArgTypes =
      | ^~~~~~~
      | const
~~~~

That's because the header file requires a compiler supporting ISO 2020 C++ language version, while some compilers defaults to an older language version. E.g. GCC 14.2.1 defaults to ISO 2017 with GNU extensions.

Please consult a documentation of your compiler, how to enable ISO 2020 mode. E.g. GCC has -std=gnu++20 option.
