### ISSUE TITLE
Future of configuration options `strict` and `skip_broken`

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#269]
Both options are somehow related from CLI `strict` = not `skip_broken` This is not valid for API or `microdnf` where `skip_broken` is ignored.

### Background
`YUM 3` has option `skip_broken`. DNF split the option into two => `strict` and `best`, but skip_broken remained as a compatibility option with `YUM`. `strict` still means two things => skip_broken (solver), `skip_unavailable` not in any repository and not installed.

### Possible solutions
We could split `strict` option, and remove or mark deprecated one of the options.

- create new configuration option `skip_unavailable`
  - it will help us to modify behavior of group - strict behavior with one unified switch
  - the name is already used by `builddep` command

- mark `strict` as deprecated
  - align `strict` = `not skip_broken`
  - or remove `strict`

- mark `skip_broken` as deprecated
  - align `strict` = `not skip_broken`
  - or remove `skip_broken`

**Comment by pkratoch** [comment]
With `strict`, I need to remember in what way it's strict, while `skip_broken` and `skip_unavailable` are more descriptive. It'd be also more straightforward to configure dnf with these two options rather than having to think how to set some combination of `strict` and another sub-option.

**Comment by m-blaha** [comment]
Maybe more examples and use cases of what currently is / is not possible can help here.
Let me summarize how I understand the problem (and please correct me if I'm mistaken).

- first problem is that we have `strict` config option (defaulting to true), but instead of having `--strict` and `--no-strict` command line options, there is `--skip-broken` which sets `strict=false`. This is confusing.
- `strict` means skip both - unavailable packages, and packages with broken dependencies. The problem is that there is no way how to skip only unavailable (group command use case) and error out on broken dependencies.

For me the best solution would be

- keep config options and command line options the same
- introduce two new config/commandline options - `skip_broken` and `skip_unavailable`, both default to false
- deprecate `strict` config option and temporarily keep the dnf4 meaning for compatibility -
    - strict=true means skip_broken=false and skip_unavailable=false
    - strict=false means skip_broken=true and skip_unavailable=true

**Comment by jan-kolarik** [comment]
I agree with previous comments. I found it better having two options (`skip_broken` and `skip_unavailable`) doing only that one thing stated in their name than one (`strict`) doing more actions in the background. Deprecating the `strict`, but keeping it there for a while sounds for me like a good way to do the transition more smoothly.

**Comment by kontura** [comment]
I am also in favor of splitting `strict`.

I would just like to mention that `skip_unavailable` is very similar to already present `skip_if_unavailable` (it affects repositories).

Given that `skip_unavailable` is used in the mentioned `builddep` and also in dnf4 in history replay how about to add the `skip_unavailable` but rename `skip_if_unavailable`?

In the man pages `skip_if_unavailable` has an explanation that it doesn't affect packages so perhaps the option is not well named anyway? Would `skip_unavailable_repositories` be too long? Currently it is just a config option.

**Comment by j-mracek** [comment]
`skip_if_unavailable` - This is a repo file configuration option, therefore renaming would be very painful. Ropo file are generated by many entities and delivered often by rpms, dnf plugins and so on.
