### ISSUE TITLE
`dnf5 install --help` does not provide help

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#317]
```
dnf5 install --help
Missing positional argument "specs" for command "install"
```
To receive a help for the command it requires provide argument

**Comment by rafagomes** [comment]
Hello @j-mracek, my name is Rafa, and I'm interested in contributing to the Fedora project. I have experience with Python, Javascript, and C++ (I want to improve that and help in any way I can). I would love to work on this issue. Can anyone guide me on how to get started with this issue? Or can I check what has been done to the group and others in the code and follow the same?

Any help would be appreciated. I don't want to start breaking crystal glasses. :)

**Comment by j-mracek** [comment]
Hello @rafagomes, thank you for the interest in DNF5 project. I will ask my colleague @jrohel to provide the initial guidance.

**Comment by rafagomes** [comment]
Thank you @j-mracek.

**Comment by rafagomes** [comment]
Thank you @jrohel 

I'll open a PR asap. <3

**Comment by praiskup** [comment]
IMO we need to take a look at [this part](https://github.com/rpm-software-management/dnf5/blob/99f6bc40f01a08f4f532c38b348ef33e1cd4e06e/dnf5/main.cpp#L673-L695).

The `--help` argument is handled if and only if no exception was thrown in `parse()`.  So should there be some fix in argument parser logic that will avoid throwing the exception with `--help` specified?

**Comment by rafagomes** [comment]
@praiskup That is what I'm planning to do. I'll try to start this today...
Maybe we need to split responsibilities... if --help/-h is passed, we don't go checking unnecessary expectations.

**Comment by praiskup** [comment]
This is IMO a high-priority issue (it is not possible to get the --help output at all in some cases).
Therefore please consider (a short-term work-around?) in #445.

**Comment by rafagomes** [comment]
Well, I was trying to make my first contribution. I'll move on to another project from Fedora then... Two things I disagree with and made me frustrated and I think is fair to give my feedback:
- I asked a question and waited for 2,5weeks to get a reply;
- When I finally have some direction I receive a "short-term workaround" for something that is not even launched.
- A PR is made in front of me. Well, I tried...

Good luck all <3

**Comment by praiskup** [comment]
@rafagomes sorry to hear that, by no means #445 was meant to **solve** this issue (that is just a related PR, see the commit message).  I am just a contributor here, not the DNF maintainer (I'm working on #414, and this issue is rather a painful thing, really).

What I'm not sure about (but my opinion has a low weight, being a random contributor) is whether this is actually an "easy fix" or a "good first issue".  Definitely doesn't look like a "low prio" thing to me.

**Comment by jrohel** [comment]
@rafagomes Thank you for your response. And I apologize for the situation. As Praiskup wrote, his PR is only a short-term solution. Since you don't want to continue, I prepared a PR with a solution.
But to be honest, I'm sad that it turned out this way. I liked that you thought about the problem at the beginning and asked for additional information. I wish your next contribution to be a success.

**Comment by rafagomes** [comment]
@praiskup @jrohel Sorry, I think my reaction was too sensitive...I was on a bad day. It was good that I saw your codes for future references...I'll try to help Fedora anyway I can...see you guys around.

**Comment by jrohel** [comment]
Fixed by https://github.com/rpm-software-management/dnf5/pull/450
