### ISSUE TITLE
[RFE] Print curl errors only once per repo

### ISSUE THREAD

**Issue by frenzymadness** [rpm-software-management/dnf5#324]
When I have a repository that is currently not available, dnf prints an error message for every try to reach the repo. For example:
```
>>> Curl error (6): Couldn't resolve host name for https://myrepo.org
>>> Curl error (6): Couldn't resolve host name for https://myrepo.org
>>> Curl error (6): Couldn't resolve host name for https://myrepo.org
>>> Curl error (6): Couldn't resolve host name for https://myrepo.org
>>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.x
```
or
```
>>> Status code: 404 for http://example.com/...
>>> Status code: 404 for http://example.com/...
>>> Status code: 404 for http://example.com/...
>>> Status code: 404 for http://example.com/...
>>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.x
```
Given the fact that the errors are exactly the same for all 4 tries, it might make sense to print it only once per repo / per error so the output in these cases would contain only the last two lines.

**Comment by jan-kolarik** [comment]
Hello and thanks for the report! 

I was looking into the current behavior and in original DNF, the eventual error reports are displayed **after** the processing is done and it is deduplicated then. In DNF5 the reports are displayed immediately to let the user know what's going on in real time, so there could be multiple reports with the same message. Therefore this is intentional behavior.

Downloading of the metadata is handled by the different component, in `librepo`. There is the `LRO_ALLOWEDMIRRORFAILURES` parameter which is by default set to `4`. IMHO in this case it could be more clever and when a serious error like the `404` happens, it should skip the mirror immediately. But this would require changing the logic of `downloader` in the `librepo`.

**Comment by frenzymadness** [comment]
Well, I don't think the reporting in real-time is a problem here but displaying the exact same error multiple times is kinda pointless. Should I report it somewhere else?

**Comment by jan-kolarik** [comment]
I wouldn't say it's pointless showing the same error multiple times as you have there the information about how many attempts were made and when the operation is taking longer time it gives you some explanation why the delay is happening...

But anyway, I got your point and I am also not satisfied with the current state. When the metadata are downloaded the progress errors could be displayed on one line and rewritten with each attempt, showing the current number of attempt instead of just filling the output with these errors. I am adding this to the backlog to the related, already existing issue #159.

Regarding the mentioned default 4 attempts to download the metadata from failing repo. What we could do about this is to handle the error from `librepo` in the metadata downloading callbacks on the `DNF5` side. There we can decide if the error is fatal and it's not worth trying the mirror again, by returning the `LR_CB_ABORT` from the callback. After this return code, `librepo` will skip the mirror immediately leaving only one error message left. I am leaving this note here so we can address it later when eventually implementing the mentioned issue.
