### ISSUE TITLE
how to add "version lock"  with dnf5 ...

### ISSUE THREAD

**Issue by Dutchglory** [rpm-software-management/dnf5#332]
how do i  add a "version lock"  with dnf5  ...  or add a version-lock plugin to dnf5

```
Package "epson-inkjet-printer-escpr-1.7.25-1lsb3.2.x86_64" is already installed with reason "User".

[verwijs@fedora ~]$ dnf5 upgrade
Updating and loading repositories:
Repositories loaded.
Package                                      Arch         Version                        Repository       Size
Upgrading:                                                                                                                                    
 epson-inkjet-printer-escpr                 x86_64       1:1.7.21-3.1lsb3.2.fc38          fedora        5.3 MiB
 replacing epson-inkjet-printer-escpr       x86_64       1.7.25-1lsb3.2                @commandline     5.4 MiB

Transaction Summary:
 Upgrading:         1 packages
 Replacing:         1 packages

```

**Comment by j-mracek** [comment]
Version lock was implemented in DNF as a plugin using rpm excludes.

The question is whether we should integrate it as a core functionality of libdnf5 and whether we cold use libsolv locking solvable.

**Comment by KraXen72** [comment]
Hello, there is a bug with the libdnf/dnf5 versionlock plugin:
versionlocked packages are still updated through packagekit (e.g. Gnome Software or KDE Discover)

relevant links:
https://bugs.kde.org/show_bug.cgi?id=473607 -> told to file in packagekit
https://github.com/PackageKit/PackageKit/issues/677 -> told to file in libdnf
https://github.com/rpm-software-management/libdnf/issues/1627 -> told that it's not going to be implemented in dnf4 since dnf5 is soon to be released.

dnf5 is now released and this bug still persists.

Please let me know if i should open a new issue and if so, where, since on all the different bug trackers i checked, everyone is just saying to report this issue somewhere else..

Thanks!
