### ISSUE TITLE
Which libdnf to use for new development?

### ISSUE THREAD

**Issue by theodor96** [rpm-software-management/dnf5#413]
I am writing a C++ program that needs to interact with the packaging system. For ensuring a long time support of the used APIs, should I be compiling against a libdnf built from [these tags](https://github.com/rpm-software-management/libdnf/tags) or [these ones](https://github.com/rpm-software-management/dnf5/tags)? Basically should it be the libdnf4 or the libdnf5? Because I saw that the offered APIs are very different. I am targeting mainly CentOS 7, 8 stream and 9 stream.

**Comment by jan-kolarik** [comment]
Hi there, the important information you mentioned is about what distribution or stream you are targeting. Speaking about CentOS 7-9, as I know there is no plan to deliver DNF5 there, because we are targeting RHEL 10 in the future which should match the CentOS 10 then. So for your purposes it should be the [`libdnf`](https://github.com/rpm-software-management/libdnf) project.

**Comment by theodor96** [comment]
Hey, thanks a lot for looking into this!

I will be using the regular `libdnf` then. Speaking of which, something that I found quite surprising when playing with it is that there are certain symbols exposed in the `so` for which the relevant headers do not get installed. Only the "c-like" headers seem to get installed when you do `make install`, but if I manually import the "cpp-like" ones I am able to call said functions/classes so for sure they are being compiled into the `so`. But maybe this is a better question for the other repository right?

Another point I wanted to raise is: any other major difference between libdnf4 and 5 besides being API and ABI incompatible? Like, I am referring to the actual data stored in the database and on disk. Say for example I have a 9 stream with the regular `dnf` installed and I do some things, could I at a later point in time use either `dnf5` CLI or its underlying library on the same system, or they're fundamentally incompatible?

**Comment by j-mracek** [comment]
LIBDNF4 has limited API not only that we provides C and Python bindings, but also not all use cases are covered. The reset of the logic is in DNF (Python). LIBDNF5 provides more functionality then LIBDNF4. In LIBDNF5 we changed a workflow related to transaction. Just in short, when you request install something - LIBDNF5 will only store the request and the request will be evaluated when resolve() is called.
I guess that the issue was resolved, therefore proposing to close the issue.
