### ISSUE TITLE
Investigate dnf requires in following packages and suggest solution to keep upgrade path in Fedora 39

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#418]

**Comment by evan-goode** [comment]
Copying some details from #411: 

- Some of the packages incorrectly requires dnf because they use API from python3-dnf therefore they must require it-> dnfdragora, dnf-automatic, ...
 - Other packages
 - I recommend to create a tracking bugzilla  or use as a tracking issue - https://bugzilla.redhat.com/show_bug.cgi?id=2166026
 - If it will be not resolved, it will break the upgrade path
   - provide patch for dnf components
   - create an issue (bugzilla) on other components and suggest a change in spec
   - create an issue (bugzilla) on other components and ask them to adopt DNF5, drop dnf require, require dnf-3 binary or remove the package from the distribution


- [ ] auter
- [ ] calamares
- [ ] copr-builder
- [ ] dnf-automatic
- [ ] dnf-plugin-diff
- [ ] dnf-utils
- [ ] dnfdragora
- [ ] etckeeper-dnf
- [ ] fedora-review
- [ ] fedora-upgrade
- [ ] kiwi-systemdeps-core
- [ ] libdnf-plugin-subscription-manager
- [ ] lpf
- [ ] mock
- [ ] osbuild
- [ ] perl-CPAN-Plugin-Sysdeps
- [ ] policycoreutils-devel
- [ ] rbm
- [ ] rpmdistro-repoquery
- [ ] subscription-manager
- [ ] supermin
- [ ] supermin-devel
- [ ] system-config-language


- [ ] Make announcement of release on Fedora devel - it will break several thinks

**Comment by evan-goode** [comment]
All the dependents of `dnf` have been notified, so this can be closed.

**Comment by FrostyX** [comment]
Thank you very much @evan-goode for doing it this way and opening PRs for all of those projects.
Good job, much appreciated.

**Comment by evan-goode** [comment]
Now that we are planning to switch to DNF 5 in Rawhide again soon, I am following up with the DNF dependents again since some of the original issues were closed without fixing the dependency on `dnf`:

- [x] auter
  - https://github.com/rackerlabs/auter/issues/245
- [x] calamares
  - https://github.com/calamares/calamares/issues/2145
- [x] cpanspec
  - https://src.fedoraproject.org/rpms/cpanspec/pull-request/2
- [x] dnfdragora
  - https://github.com/manatools/dnfdragora/issues/214
- [x] etckeeper-dnf
  - https://src.fedoraproject.org/rpms/etckeeper/pull-request/6
- [x] fedora-review
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209416
- [ ] kiwi-systemdeps-core
  - https://github.com/OSInside/kiwi/issues/2300
  - Resolved in upstream, [downstream spec](https://src.fedoraproject.org/rpms/kiwi/blob/rawhide/f/kiwi.spec) needs to be regenerated from their template?
- [x] lpf
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209396
- [x] mkosi-initrd
  - https://src.fedoraproject.org/rpms/mkosi-initrd/pull-request/1
- [x] osbuild
  - https://github.com/osbuild/osbuild/issues/1315
- [x] perl-CPAN-Plugin-Sysdeps
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209402
- [x] rbm
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209405
- [x] rpmdistro-repoquery
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209408
  - https://src.fedoraproject.org/rpms/rpmdistro-repoquery/pull-request/1
- [x] system-config-language
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209413

**Comment by evan-goode** [comment]
One we missed since it depends on `python2-dnf` and `yum`, not `dnf`:
- [x] punki
  - https://pagure.io/pungi/issue/1747
