### ISSUE TITLE
Save system state even after unsuccessful rpm transaction?

### ISSUE THREAD

**Issue by m-blaha** [rpm-software-management/dnf5#433]
The thing is that `rpm_transaction.run()` returns an error code also in situation when only a scriptlet failed, but all the packages are installed / removed / upgraded.
Currently the system state is written only when `rpmtsRun()` call returned `0`. Does it make sense to change this condition to `ret >= 0`? I haven't investigated the meaning of the return value on rpm side yet.

**Comment by j-mracek** [comment]
Thank you very much for highlighting the issue. I think that there is not a correct solution, because we have only bad solutions.

Basically we have two opposite solution - save the new state or not save. And I think both are not a good solution.

Example 1:
install a package and its dependency. The dependency was installed correctly, but install of other package failed therefore it is not on the system. If we will save the state we will see dependency installed as dep, and not installed package as user. If we will not store the change then only installed dependency will be without information - therefore it will be handled as user package.

Example 2:
Remove a package but it failed and package was not removed. When we will update the system state then package will have no reason, repoid in db, but if we will not update then the information will be still there.

I think that the best solution is between both solutions. But it will require not a trivial logic that will compare the actual state of installed content with planned content and update the system state after evaluation for particular element.

**Comment by m-blaha** [comment]
I ran into interesting variation of the Example 1:

- package `basesystem` requires `filesystem`
- package `filesystem` has failing post-install scriptlet

```
❯ dnf5 install basesystem
Updating and loading repositories:
Repositories loaded.
Package                         Arch    Version                    Repository        Size
Installing:                                                                              
 basesystem                     noarch  11-14.fc37                 fedora         0.0   B
Installing dependencies:                                                                 
 fedora-gpg-keys                noarch  37-2                       updates      120.7 KiB
 fedora-release                 noarch  37-16                      updates        0.0   B
 fedora-release-common          noarch  37-16                      updates       17.8 KiB
 fedora-release-identity-basic  noarch  37-16                      updates      668.0   B
 fedora-repos                   noarch  37-2                       updates        4.5 KiB
 filesystem                     x86_64  3.18-2.fc37                fedora       106.0   B
 setup                          noarch  2.14.1-2.fc37              fedora       718.6 KiB

------ 8< ------

Running transaction
[ 1/10] Verify package files                     100% | 380.0   B/s |   8.0   B |  00m00s
>>> Running pre-transaction scriptlet: filesystem-0:3.18-2.fc37.x86_64
>>> Stop pre-transaction scriptlet: filesystem-0:3.18-2.fc37.x86_64
[ 2/10] Prepare transaction                      100% | 421.0   B/s |   8.0   B |  00m00s
[ 3/10] Installing fedora-release-identity-basic 100% | 225.6 KiB/s | 924.0   B |  00m00s
[ 4/10] Installing fedora-gpg-keys-0:37-2.noarch 100% |   6.7 MiB/s | 163.6 KiB |  00m00s
[ 5/10] Installing fedora-release-common-0:37-16 100% |   3.6 MiB/s |  21.9 KiB |  00m00s
[ 6/10] Installing fedora-release-0:37-16.noarch 100% |   0.0   B/s | 124.0   B |  00m00s
[ 7/10] Installing fedora-repos-0:37-2.noarch    100% |   5.2 MiB/s |   5.3 KiB |  00m00s
[ 8/10] Installing setup-0:2.14.1-2.fc37.noarch  100% |  35.3 MiB/s | 723.7 KiB |  00m00s
>>> Running post-install scriptlet: setup-0:2.14.1-2.fc37.noarch
>>> Stop post-install scriptlet: setup-0:2.14.1-2.fc37.noarch
[ 9/10] Installing filesystem-0:3.18-2.fc37.x86_ 100% | 667.0 KiB/s | 212.1 KiB |  00m00s
>>> Unpack errro: filesystem-0:3.18-2.fc37.x86_64
[ 1/10] Installing basesystem-0:11-14.fc37.noarc 100% |  10.1 KiB/s | 124.0   B |  00m00s
Transaction failed: Rpm transaction failed.
```

So the transaction correctly failed, but from rpm's point of view the `basesystem` package is installed even without it's dependency:

```
❯ rpm -q basesystem
basesystem-11-14.fc37.noarch

❯ rpm -q filesystem
package filesystem is not installed
```

Should this be considered an rpm bug?

**Comment by j-mracek** [comment]
I don't think that this is a bug in RPM. RPM can install packages in free order. What change the order is `requires-pre`.
