### ISSUE TITLE
Replace gpgme by another Open PGP implementation

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#438]
DNF5 indirectly requires gpgme thru librepo.

We use for GPG verification RPM API but additionally to that we need some features from GPG me

We verify RPMs and repository metadata

### RPMs workflow
No planned changes in comparison to DNF4
Check RPM using GPG key from RPMDB, if it failed import new key and try again

### Repository metadata workflow
We can improve user experience by using imported keys from RPM DB
Check metadata using GPG key from local user specific per repository location, if it failed check metadata using GPG key from rpm DB , if it failed import new key to local user specific location and try again with that source.

The question is whether gpg keys should be shared for all repositories in single key ring or whether they should live in specific directory like they do now.

- [x] Investigate what is missing in RPM API
- [x] Replace GPGME with RPM API

**Comment by m-blaha** [comment]
As far as I remember, one thing that is missing in RPM API is ability to extract information about the key (keyid, userid, fingerprint, and URL). This information is then presented to the user with confirmation question whether they want to import the key. So we temporarily used gpgme for this.

**Comment by nwalfield** [comment]
`pgpDigParamsUserID` can be used to get the User ID, `pgpPubkeyFingerprint` returns the fingerprint, and `pgpPubkeyKeyID` returns the Key ID.  I don't know what you are thinking of with "URL."  That's not standard, AFAIK.

**Comment by m-blaha** [comment]
It's quite possible that due to my inexperience with PGP I've called rpm API with incorrect inputs. I'll give it a try again.
As far ad `URL` is concerned - it's the URL the key was downloaded from. You are right that it's not part of the key itself, we store this info separately.

**Comment by jrohel** [comment]
Some time ago I extended the API for working with OpenPGP keys of the "librepo" library. It remained backwards compatible.
Then I removed the dependency on "GpgMe" from "libdnf5", instead the new code uses the "librepo" library API.

And now I am rewriting the OpenPGP support in the "librepo" library. I am removing the dependency on "GpgMe". I use library "librpm" instead.

So far I've run into these issues:
- `pgpParsePkts` **function parses only first ascii-armor block** https://github.com/rpm-software-management/rpm/issues/2487
    **I solved it by an ugly but working hack.**

- `pgpParsePkts` **function supports only "PGP PUBLIC KEY BLOCK" block**. Parsing "PGP SIGNATURE" is needed and missing.
   I found it works with "rpm-sequoia" backend, **the problem is with internal librpm implementation.**

- `pgpDigParamsUserID` **function returns only primary user id**.
    **Please, improve the API so that all user IDs can be retrieved.**
 
- `pgpDigParamsUserID` **return an empty string when "rpm-sequoia" backend is used**. Internal "librpm" implementation returns user id.

- I can get key fingerprint using `pgpPubkeyFingerprint` function.
  **But how to get fingerprint of subkey?**

**Comment by nwalfield** [comment]
Hi, @jrohel,

Do you think these are issues with dnf5 or with rpm?  If you think the issues are with rpm or rpm-sequoia, then it is probably better to open an issue in that project (and perhaps link to those issues from here).  Also, I'd recommend opening a separate issue for each of your issues, and when possible include a reproducer.  For instance, you mention that `pgpDigParamsUserID` returns an empty string when using rpm-sequoia.  I took a quick look at the code, and this would happen when you pass an invalid certificate (according to the crypto policy).  But, I can't tell if that is your problem.  Thanks.

**Comment by jrohel** [comment]
@nwalfield I wanted to note the status of the GpgMe replacement here. But you're right, I should report issues to the respective projects.
