### ISSUE TITLE
Missing virtual provides for command

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#566]
DNF5 as well as dnf has modular command therefore therefore it is quite useful to mark packages that provides particular command by virtual provide.

In DNF4 we use `dnf-command(<command_name>)` and when user requests unknown command it suggest to install such a command using the virtual provide.

What about to use the sama schema for `dnf5`?

Because dnf5 provides DNF and man pages refers to dnf including examples we can use `dnf-command(<command_name>)`.

Or we can use `dnf5-command(<command_name>)`.

**Comment by jkonecny12** [comment]
We are facing this issue on https://github.com/rhinstaller/anaconda/actions/runs/5372767043/jobs/9746479214#step:3:290 -- I'll fix it in our tests to use the package directly but would be great to have resolved soon to avoid another issues like this.

Also couldn't this be resolved based on the DNF version. For so it would always install the correct version? My point is that it will break stuff if you add a new provides. However, I'm not sure how this is implemented.

**Comment by evan-goode** [comment]
I think the only option here is to use `dnf5-command(<command_name>)` if we must support having a DNF 4 and DNF 5 stack installed simultaneously.

If DNF 5 plugins provided `dnf-command(<command_name>)`, then imagine the following situation:
- User has `dnf5`, `python3-dnf` and `dnf-plugins-core` installed, but they're missing `dnf5-plugins`.
- User wants to use `dnf5 builddep`, but `dnf5 install dnf-command(builddep)` will do nothing since `dnf-plugins-core` already provides `dnf-command(builddep)`.

A possibility is to have DNF 4 plugins instead provide `dnf4-command(<command_name>)` in Fedora 39+, but that seems like it could be messy.
