### ISSUE TITLE
A Provide passed as an explicit argument to "dnf install" is ignored if a package of the name exists

### ISSUE THREAD

**Issue by ppisar** [rpm-software-management/dnf5#620]
I found that explicitly passed Provide to "dnf install" is ignored if it there is a package of the same name. Let's have 3 packages "foo", "bar", and "indirect":

~~~~
Name:           foo
Version:        0
Release:        0%{?dist}
Summary:        DNF ignores explicit provides
License:        gpl-3.0-or-later
BuildArch:      noarch
Requires:       does-no-exists

%description
If DNF is asked to install something and the something exists as a package
name and as a provide in a different package, DNF stubbornly insists on the
named package, even if the package cannot be satisfied.

%package -n bar
Summary:        text
Provides:       foo = 1

%description -n bar
Text.

%package -n indirect
Summary:        text
Requires:       foo

%description -n indirect
Text.

%build

%install

%files
%files -n bar
%files -n indirect

%changelog
* Tue Apr 14 2015 Petr Pisar <ppisar@redhat.com> - 0.0
- First example
~~~~

I would expect "dnf install foo" to install package bar.  But DNF5 even does not consider it:

~~~~
# dnf5 --enablerepo dnfprovidesbug --assumeno install 'foo'
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
Problem: conflicting requests
  - nothing provides does-no-exists needed by foo-0-0.fc39.noarch
~~~~

While installing "foo = 1" which is provided by bar works:

~~~~
# dnf5 --enablerepo dnfprovidesbug --assumeno install 'foo = 1'
Updating and loading repositories:
Repositories loaded.
Package                         Arch     Version                         Repository                Size
Installing:                                                                                            
 bar                            noarch   0-0.fc39                        dnfprovidesbug         0.0   B

Transaction Summary:
 Installing:        1 packages

Total size of inbound packages is 6 KiB. Need to download 6 KiB.
After this operation 0 B will be used (install 0 B, remove 0 B).
Operation aborted by the user.
~~~~

Also installation by an indirect dependency works:

~~~~
# dnf5 --enablerepo dnfprovidesbug --assumeno install 'indirect'
Updating and loading repositories:
Repositories loaded.
Package                         Arch     Version                         Repository                Size
Installing:                                                                                            
 indirect                       noarch   0-0.fc39                        dnfprovidesbug         0.0   B
Installing dependencies:                                                                               
 bar                            noarch   0-0.fc39                        dnfprovidesbug         0.0   B

Transaction Summary:
 Installing:        2 packages

Total size of inbound packages is 12 KiB. Need to download 12 KiB.
After this operation 0 B will be used (install 0 B, remove 0 B).
Operation aborted by the user.
~~~~

It seems that DNF handles explicitly passed RPM symbols differently from other dependencies discovered inside RPM packages. I thought that it intentionally prefers package names over Provides. But the following command suggests it's a bug in parsing command line arguments:

~~~~
# dnf5 --enablerepo dnfprovidesbug --assumeno install 'foo '
Updating and loading repositories:
 dnfprovidesbug                                                100% |   0.0   B/s |   3.0 KiB |  00m00s
Repositories loaded.
Package                         Arch     Version                         Repository                Size
Installing:                                                                                            
 bar                            noarch   0-0.fc39                        dnfprovidesbug         0.0   B

Transaction Summary:
 Installing:        1 packages

Total size of inbound packages is 6 KiB. Need to download 6 KiB.
After this operation 0 B will be used (install 0 B, remove 0 B).
Operation aborted by the user.
~~~~

Pay attention to the trailing space at foo argument. I guess a root cause is that DNF first matches positional arguments against package names. If there is a match, it prematurely ends and does not look into Provides of other packages. If there is no match, it matches against provides.

I discovered this bug when using "dnf builddep" subcommand. Handling BuildRequires in spec files is also affected.

Observed with dnf5-5.0.14-1.fc39.x86_64.
I tried DNF4 and it also has this bug.

I find this behavior faulty. Especially because it break my <https://ppisar.fedorapeople.org/postmodular/> concept which is based on provides substituting package names.

**Comment by j-mracek** [comment]
> I discovered this bug when using "dnf builddep" subcommand. Handling BuildRequires in spec files is also affected.

I think this is not valid for DNF4. DNF4 installs buildrequires according to provide or file pattern.

But the issue is valid for DNF5
```
    for (const auto & spec : install_specs) {
        if (libdnf::rpm::Reldep::is_rich_dependency(spec)) {
            goal->add_provide_install(spec);
        } else {
            goal->add_rpm_install(spec);
        }
    }
```
In DNF4 it install reldep as provide or file.

**Comment by j-mracek** [comment]
The remaining part - handling of a user specified argument for install command. It has two different part

1. User expectation
2. Implementation

DNF does not know what user want to do but it makes a guess by trying a different option. In the first place we suggest that provided string is related to NEVRA. If we find a match than we use the match and process it. We do not pass that result directly to solver, but we split package set according to name (Argument `dnf-*` result in installation of multiple packages) and then optionally we add obsoletes of matched packages. This behavior ensures that it is necessary to run upgrade after install to ensure the best candidate (obsoleter) is installed.

We don't use provides in the first place because they add more options and in combination with globs it would results in huge installation set. We also do not add obsoletes to the job. From user perspective it would be not nice to ask to install `a` and it will install `b` just because it provides `a`. In enterprise it is expected that DNF is supposed to fail even if `a` is present, installable but the latest version (best candidate) has broken dependencies.

If we will provide requested behavior - we will hide the issue with `foo` and provide alternative. If user want to install `foo` and we will install `bar` we will not meet user expectation. We don't know that situation with `foo` and its broken dependencies is expected therefore we should not report as an issue.

The implementation is also something that makes me nervous. Our standard work flow is that we create job or jobs for each request and then we run it once and then we only play with installonly packages. Alternatively we set jobs to install according the name search and it fail we can create a failing job with the provide set. This get complicated when multiple jobs are in transaction, then we start to modify them and we can get another set of issues and again and again. If we will use directly the install provide job we might get difficulty with preferring package with the same name as provide.

**Comment by j-mracek** [comment]
In most of cases dnf handles argument by the same way for transaction commands. As a example I can use`install` or upgrade command.

**Comment by ppisar** [comment]
Recently DNF5 stopped supporting uninstallation by a Provide. It's obvious DNF5 does want support my workflow. I'm closing this issue.
