### ISSUE TITLE
openQA modularity tests fail with dnf5: `dnf module list` lists nothing, `dnf module enable mysql:8.0` and `dnf module install mysql:8.0/server` fail with unknown argument errors

### ISSUE THREAD

**Issue by AdamWill** [rpm-software-management/dnf5#689]
We have a test in openQA that tests various dnf modularity commands. Since dnf5 became the default, it's failing in several ways.

* One test runs `dnf module list --disablerepo=updates-modular --disablerepo=updates-testing-modular` - the disabling is to try and ensure we get consistent output - and expects to see...something. That command prints nothing at all with dnf5-5.0.14-2.fc39.
* Another test runs `dnf module enable -y mysql:8.0`. That fails with error `Unknown argument "mysql:8.0" for command "enable".`
* Another test runs `dnf module install -y mysql:8.0/server`. That fails with a similar "Unknown argument" error.

See https://openqa.fedoraproject.org/tests/1997217#step/modularity_install_module

**Comment by pkratoch** [comment]
The module commands are mostly not implemented yet. Here is the tracking issue: https://github.com/rpm-software-management/dnf5/issues/146

The module enable should be available since dnf5-5.0.15.

And there was also an issue about some sub-commands being visible on CLI, although not yet implemented. This was fixed by: https://github.com/rpm-software-management/dnf5/issues/642 (also since dnf5-5.0.15).

**Comment by jan-kolarik** [comment]
I am closing this as we have a tracking issue for all the missing subcommands.
