### ISSUE TITLE
snapper broken

### ISSUE THREAD

**Issue by 11raob** [rpm-software-management/dnf5#702]
snapper will not make pre and post automatic snapshots with dnf5 as it did with version 4.

**Comment by jrohel** [comment]
DNF4:
Yes, there is a `snapper` plugin for dnf4 (it's part of dnf-plugins-extras). The plugin is written in Python and is only used when the high-level DNF Python plugin API is used. So old `microdnf`, `PackageKit`, ... and other applications using libdnf directly will not call this plugin.
Additionally, I added support for C plugins directly to libdnf. These will be used by old `microdnf`, `Packagekit`, ... but not dnf.

libdnf5:
Here is support for C++ plugins that will be used by all applications using libdnf5. The `snapper` plugin is not implemented. The question is whether it will be necessary. In dnf4 there is a `post-transaction-actions` plugin that allows you to run external applications after a transaction. This is insufficient for a `snapper` plugin. That's why I implemented a new `actions` plugin for libdnf5. This plugin allows external applications to be launched even before a transaction (callback can be defined). And it supports working with libdnf5 configuration. And much more.

Example configuration for libdnf5 `actions` plugin (version 0.2.0), that emulates dnf4 `snapper` plugin:
```
# Creates pre snapshot before the transaction and stores the snapshot number in the "tmp.snapper_pre_number"  variable.
pre_transaction::::/usr/bin/sh -c echo\ "tmp.snapper_pre_number=$(snapper\ create\ -t\ pre\ -p)"

# If the variable "tmp.snapper_pre_number" exists, it creates post snapshot after the transaction and removes the variable "tmp.snapper_pre_number".
post_transaction::::/usr/bin/sh -c [\ -n\ "${tmp.snapper_pre_number}"\ ]\ &&\ snapper\ create\ -t\ post\ --pre-number\ "${tmp.snapper_pre_number}"\ ;\ echo\ tmp.snapper_pre_number
```

I am preparing documentation for the libdnf5 "actions" plugin https://github.com/rpm-software-management/dnf5/pull/618.
And I'm also preparing a default configuration.

**Comment by jpjubenot** [comment]
Hi Guys
Any update or workaround regarding this feature ?
I am really interested by dnf5, but I don't want to lose this dnf4 plugin.

**Comment by jan-kolarik** [comment]
Hello, as mentioned by @jrohel, we have a more powerful `actions` plugin implemented for dnf5. You can find documentation for it [here](https://dnf5.readthedocs.io/en/latest/libdnf5_plugins/actions.8.html), along with an example demonstrating how to emulate the behavior of the `snapper` plugin. Is it OK like that? If so, we can proceed to close this issue.

**Comment by jpjubenot** [comment]
Ok, I got it Jan-kolarik
I will proceed like explained with this pre and post-transaction.
You can close this issue.
Thx .

**Comment by LuanVSO** [comment]
modified the action config to also include a description for the snapshot
```
# Get snapshot description
pre_transaction::::/usr/bin/sh -c echo\ "tmp.cmd=$(ps\ -o\ command\ --no-headers\ -p\ '${pid}')"
# Creates pre snapshot before the transaction and stores the snapshot number in the "tmp.snapper_pre_number"  variable.
pre_transaction::::/usr/bin/sh -c echo\ "tmp.snapper_pre_number=$(snapper\ create\ -t\ pre\ -p\ -d\ '${tmp.cmd}')"

# If the variable "tmp.snapper_pre_number" exists, it creates post snapshot after the transaction and removes the variable "tmp.snapper_pre_number".
post_transaction::::/usr/bin/sh -c [\ -n\ "${tmp.snapper_pre_number}"\ ]\ &&\ snapper\ create\ -t\ post\ --pre-number\ "${tmp.snapper_pre_number}"\ -d\ "${tmp.cmd}"\ ;\ echo\ tmp.snapper_pre_number\ ;\ echo\ tmp.cmd
```

**Comment by satankush** [comment]
> modified the action config to also include a description for the snapshot
> 
> ```
> # Get snapshot description
> pre_transaction::::/usr/bin/sh -c echo\ "tmp.cmd=$(ps\ -o\ command\ --no-headers\ -p\ '${pid}')"
> # Creates pre snapshot before the transaction and stores the snapshot number in the "tmp.snapper_pre_number"  variable.
> pre_transaction::::/usr/bin/sh -c echo\ "tmp.snapper_pre_number=$(snapper\ create\ -t\ pre\ -p\ -d\ '${tmp.cmd}')"
> 
> # If the variable "tmp.snapper_pre_number" exists, it creates post snapshot after the transaction and removes the variable "tmp.snapper_pre_number".
> post_transaction::::/usr/bin/sh -c [\ -n\ "${tmp.snapper_pre_number}"\ ]\ &&\ snapper\ create\ -t\ post\ --pre-number\ "${tmp.snapper_pre_number}"\ -d\ "${tmp.cmd}"\ ;\ echo\ tmp.snapper_pre_number\ ;\ echo\ tmp.cmd
> ```

would also add -c\ number\ to use the number cleanup algorithm like the dnf4 plugin did

**Comment by rnayabed** [comment]
> would also add -c\ number\ to use the number cleanup algorithm like the dnf4 plugin did

@satankush how to do it? n00b here :D thanks

**Comment by itafraze** [comment]
Hi. Just landed here as this page is still among the top results when searching for a solution. As a reminder to my future self, check [Dropping_the_Snapper_plugin](https://fedoraproject.org/wiki/Changes/SwitchToDnf5#Dropping_the_Snapper_plugin) changelog and [an-example-actions-file](https://dnf5.readthedocs.io/en/latest/libdnf5_plugins/actions.8.html#an-example-actions-file) to configure snapper.
