### ISSUE TITLE
repoquery --qf newline behavior changed

### ISSUE THREAD

**Issue by juhp** [rpm-software-management/dnf5#709]
```shellsession
$ sudo dnf-3 rq -q --qf "%{name}" bash coreutils
bash
coreutils
$ rpm -q dnf5
dnf5-5.0.15-2.fc39.x86_64
$ sudo dnf rq -q --qf "%{name}" bash coreutils
bashcoreutils
```
Yes it may seem a smaller thing, but this change of behavior breaks scripts etc...
(even if consistent with rpmquery).

**Comment by juhp** [comment]
Just want to add that this makes it rather hard to support `dnf repoquery` across dnf-4 and dnf5 since they behave differently.

**Comment by jn64** [comment]
It was noted as an intentional change to match rpm -q --qf

https://github.com/rpm-software-management/dnf5/blob/9a42f5d8a18966e30b75da99fd5cbdaaea2a05d8/doc/changes.rst?plain=1#L141-L142

**Comment by kontura** [comment]
I was thinking that the new behavior is not only consistent with rpm `--queryformat` but it is also more powerful. Before users had to have the new line even if unwanted now they can choose. The option is more flexible.

Since we are switching to dnf5 which includes other changes I thought it was a good time for such an improvement.

However it is indeed a breaking change.

**Comment by jlebon** [comment]
Additionally, `\t` is no longer interpreted.

**Comment by ppisar** [comment]
> Additionally, `\t` is no longer interpreted.

I moved your finding to a separate issue #1916 as it is an independent problem.

**Comment by ppisar** [comment]
The new-line issue was already rejected by DNF developer in Bugzilla <https://bugzilla.redhat.com/show_bug.cgi?id=2324312>. Closing this issue.
