### ISSUE TITLE
Use sticky vendors by default

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/dnf5#712]
### Description of request

Over the years, we've had a number of complaints of unintended package switching between providers. While users can use versionlock and excludes to manually constrain things, it has become pretty obvious that the intent is to "lock on" to particular providers of packages when initially installed or explicitly switched.

In Fedora, the following cases exist today:

* `-freeworld` packages from third party sources
* Alternative builds of packages from COPR/OBS
* Personal packages replacing distro packages

While those cases may exist for RHEL/CentOS, there is also the case of CentOS SIG packages replacing distro packages.

### Benefit to Fedora/CentOS/RHEL

By switching this on by default (`allow_vendor_change=False`), there will be less surprises with upgrades, and the solver can make more educated choices based on the expected desires of the user.

### Benefit to (open)SUSE

This is already the default behavior in SUSE distributions, and DNF v4 in openSUSE is configured to have sticky vendors on by default. This would just make it the upstream default for DNF v5 and make it easier in SUSE distributions.

**Comment by kontura** [comment]
I believe this has already been done: https://github.com/rpm-software-management/dnf5/pull/623

We have already had a number of reports why are packages not updating.
I like the suggestion from: https://bugzilla.redhat.com/show_bug.cgi?id=2219624 to also add a warning like:
`Warning: 1 vendor change prevented, consider allow_vendor_change=true`

**Comment by Conan-Kudo** [comment]
At least in DNF 4, sticky vendors can be overridden if you use either `dnf repository-packages` to install or if you specify the full NEVRA to install/upgrade to. If we port over `dnf repository-packages` functionality to DNF 5, that could be used to suggest how to switch vendors for a package.

**Comment by praiskup** [comment]
As this got reverted by https://github.com/rpm-software-management/dnf5/pull/745 and https://github.com/rpm-software-management/dnf5/issues/750 was created, I think we should reopen this one?

**Comment by pemensik** [comment]
I think vendor changes should be highlighted somehow. Either put then on top or bottom of the list of upgraded packages. Make the vendor change bold if possible. I think vendor updates should get higher visibility to ensure this is wanted and intended, before I press Y to start upgrading. Explicitly showing change of vendor repository used for the package would be good.

While I like this idea in general, it has broken too many workflows on Fedora rawhide. It *needs* to communicate better what happens or why it does not.

**Comment by Conan-Kudo** [comment]
It absolutely needs communication. Zypper uses a third color (yellow) for vendor changes with the colorized output. It also breaks out vendor changes into a separate set of rows, which I think makes sense for us to do too.

**Comment by evan-goode** [comment]
I'm pasting in a summary that jan-kolarik wrote on our team Jira in March 2025. Maybe we can edit this comment to track progress on each of these problems:

<hr>

There seem to be three main issues related to package vendoring:

* Problems with the current behavior of `allow_vendor_change=False`
* Missing an easy way to request specific dnf actions using a given spec on top of a specified repository
* dnf reporting of package vendor changes should be more concise and visible

## Problems with the current behavior of `allow_vendor_change=False`

Three issues have been reported in upstream tickets:

* Command-line packages cannot replace installed ones from a different vendor
  * This limitation prevents installing certain updates or alternatives.
  * A possible solution could be simply allowing vendor changes in this scenario.
* Disabling a COPR repository results in operation refusal
  * This happens because of vendor differences between incoming and installed packages.
  * While the refusal is expected, we could provide clearer error messages to help users understand the issue.
* Cryptic solver messages
  * There are two main cases:
    * **Conflicting package/vendor errors** – These could be handled in the process_solver_problems method by querying source and target solvables along with their vendor IDs, improving error explanations.
    * **"Nothing to do" cases** – Ideally, we should be able to anticipate these situations when processing user requests (adding actions to the goal) based on installed packages, available queries, and repository IDs. However, solving this might be more complex than the first case.

## Missing an easy way to request specific dnf actions using a given spec on a specified repository

In dnf4, running repository-specific actions requires using repository-packages commands and their subcommands, which feels cumbersome. It forces us to create equivalent commands for all individual dnf operations, just to provide repository-specific functionality.

One possible solution is to introduce a special parameter like --use-repo or allow syntax like dnf install pkg-1.0.0@repo1.

In any case, this can probably (or maybe even always) be worked around by listing the available packages for a given name, like dnf repoquery pkg --info. Alternatively, we could extend dnf search to include the repository name in case of duplicates. The user can then check the vendors (repositories) and install the specific package they need. I don’t think a NEVRA clash is expected, especially with COPR repositories.

egoode: Would be resolved by `--from-repo` flag: https://github.com/rpm-software-management/dnf5/issues/2279

## dnf reporting of package vendor changes should be more concise and visible

If the changes mentioned above aren’t sufficient, we should enhance the transaction output by adding a highlight or a dedicated section for vendor changes. It could also make sense to merge this effort with the updates planned for the verbose/non-verbose transaction table output.

**Comment by Conan-Kudo** [comment]
It would also make sense to use a dedicated color in colorized terminal output for vendor changes. Zypper does this so that you cannot miss vendor changes.

**Comment by Conan-Kudo** [comment]
> Command-line packages cannot replace installed ones from a different vendor
>  * This limitation prevents installing certain updates or alternatives.
>  * A possible solution could be simply allowing vendor changes in this scenario.

There should be some kind of warning in the UI that this is happening even if it's allowed by default. The biggest implication of such a thing is that you're taken off the vendor track and can't receive updates from a repository (unless we also enhance DNF to always allow `@commandline` source packages to allow vendor switching even with sticky vendors).

**Comment by evan-goode** [comment]
Fedora change proposal to set `allow_vendor_change=false`: https://fedoraproject.org/wiki/Changes/DisableVendorChangeByDefault
