### ISSUE TITLE
DNF should let users know of available updates

### ISSUE THREAD

**Issue by vmojzis** [rpm-software-management/dnf5#734]
```
# dnf repoquery libselinux
libselinux-0:3.5-4.fc39.i686
libselinux-0:3.5-4.fc39.x86_64
# rpm -qa libselinux
libselinux-3.5-1.fc39.x86_64
# dnf update libselinux
Nothing to do.
```

When there is a newer package version available, but is missing some dependencies, DNF ignores it as long as "--best" is not used. The user clearly wants to update the package, so the response should not be "Nothing to do" (as this strongly implies that the system contains the latest version of the package). DNF should instead let the user know there is an updated version of the requested package available and they can install it using "--best".

For more details see: https://github.com/rpm-software-management/dnf5/issues/698

**Comment by j-mracek** [comment]
I am really sorry for late response. I believe that the reported issue is related to a different vendor of packages, therefore with `allow_vendor_change=false` it is expected behavior. If the best would result the situation, dnf creates a warning when package (best candidate) has broken dependency. The default for the option was reverted to `true` therefore I believe that the issue is resolved. Please feel free to reopen the issue with additional data if my suggestion is incorrect.
