### ISSUE TITLE
Exclude handling is different in dnf5

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#763]
Hopefully I can explain this :)
In osbuild-composer we have lists of packages to be installed, and lists of packages to exclude.

In this specific case we require packages that depend on `util-linux` (this is RHEL, not Fedora where the core was split out into a separate subpackage. We also exclude `eject`, which is provided by `util-linux`.

When depsolving these requirements using dnf4 it depsolved successfully and installs `util-linux` despite `eject` being excluded.

But when using dnf5 the depsolving fails because it cannot install `util-linux`.

I'm sure there are more examples of this, probably even on Fedora, but my current test case uses RHEL.

```
#!/usr/bin/python3

import sys

import libdnf5
from libdnf5.base import GoalProblem_NO_PROBLEM as NO_PROBLEM

URL = "https://rpmrepo.osbuild.org/v2/mirror/public/el8/cs8-x86_64-baseos-20220501/"

base = libdnf5.base.Base()
base.load_config_from_file()

conf = base.get_config()
conf.zchunk = False
conf.optional_metadata_types = ['comps', 'filelists']
conf.cachedir = "/tmp/exclude-test/"
base.setup()

# Setup a single repo to use
sack = base.get_repo_sack()
repo = sack.create_repo("test-exclude")
repo_conf = repo.get_config()
repo_conf.name = "el8 repo"
repo_conf.baseurl = URL

# exclude eject, provided by util-linux
repo_conf.excludepkgs = ["eject"]

print("update and load enabled repos...")
sack.update_and_load_enabled_repos(False)
print("done.")

# Install device-mapper which requires util-linux
goal = libdnf5.base.Goal(base)
goal.add_rpm_install("device-mapper")

transaction = goal.resolve()
if transaction.get_problems() != NO_PROBLEM:
    print("PROBLEM:")
    print("\n".join(transaction.get_resolve_logs_as_strings()))
    sys.exit(1)

print("PACKAGES:")
for tsi in transaction.get_transaction_packages():
    print(tsi.get_package().get_nevra())
```

**Comment by pkratoch** [comment]
Also using CLI instead of the script: `dnf5 --repofrompath=r,https://rpmrepo.osbuild.org/v2/mirror/public/el8/cs8-x86_64-baseos-20220501/ --exclude eject install device-mapper`

I couldn't reproduce it with dummy packages - when I created dummy package `util-linux` that only provided `eject` and `device-mapper` that only required `util-linux`, then dnf5 installed `device-mapper` even though `eject` was excluded.

But I could reproduce it when I also added `/usr/bin/eject` to the `%files` section of `util-linux`.
