### ISSUE TITLE
[Feature Request] DNF P2P downloads

### ISSUE THREAD

**Issue by SethDusek** [rpm-software-management/dnf5#841]
Hi, not sure if this is the right place to post feature requests but I would like to propose a feature for DNF5: P2P downloads over LAN. This can reduce bandwidth requirements for organizations with large fedora deployments and is also useful for home users as well (I have a fairly slow by modern standards internet connection and would prefer if packages downloaded on one of my machines get seamlessly downloaded by the other)

Currently there are 2 ways to do this: setting up your own private mirror and the dnf-local-plugin. Setting up a mirror isn't feasible for most people as it requires a lot of storage and bandwidth. 

The dnf-local-plugin which is what I've been using does well but comes with its own challenges:

- Dnf-local only creates and scans a local repository for packages. Sharing this across the network requires use of some networked filesystem like NFS/Samba, which can be tricky to setup
- Using a networked filesystem (as far as I can tell atleast) requires one central server on the network to download and upload packages from
- Maintaining the local repository dnf-local creates also requires its own management to remove outdated packages (creating timers to remove stale packages, etc)
- If the networked filesystem is not available when DNF refreshes its metadata, all the packages will be downloaded from the external repository instead of the local one
- It's not clear to me if dnf-local-plugin will be supported in DNF5. It seems like a plugin that's not used very commonly so it might be some time before someone ports it to DNF5

IMO a p2p solution (maybe built inside of the dnf5daemon) would be helpful. A client could then request packages from devices on the network (if they have it in their cache) and download it from there instead of the external mirror

**Comment by ppisar** [comment]
On Fedora devel list is the same problem discussed in scope of firmware updates. I think it does not make sense to implement  a peer-to-peer file sharing in every application separately.

Instead, there should be a single localhost service where DNF would "upload" its cached files and where it attempted to retrieve files before getting them from a mirror. I'm not an expert on peer-to-peer systems, but I think that doing it properly is not easy (maintaining a dictionary of advertised files, sharing it with peers, invalidating entries, blocking rogue peers etc.) One also has to be able to limit what repositories can be shared. DNF cannot publish all packages automatically, because there can be repositories with a proprietary content.

**Comment by j-mracek** [comment]
I believe that such a request is not deliverable in a near or even distant future, therefore I think that it is a good candidate to close the request.

**Comment by ppisar** [comment]
I agree. Once there is such a service DNF can use, feel free to open a new request. Now, users are advised to place a caching proxy between them and the mirror and configure curl library to use it with http_proxy and https_proxy environment variables.
