### ISSUE TITLE
repoquery --queryformat should handle tags case insesitively

### ISSUE THREAD

**Issue by tpgxyz** [rpm-software-management/dnf5#861]
Hi,
I noticed that dnf5 repoquery has some discrepancies compared to dnf4

1. queryformat argument

`[tpg@omv-rockpro64 mdv-next]$ dnf repoquery -q --latest-limit=1 --qf %{NAME} --whatrequires make
basesystem-build
dkms
fontpackages-tools
kernel-desktop-devel
kernel-rc-desktop-devel
kernel-rc-server-devel
kernel-rc-source
kernel-server-devel
kernel-source
kernel5.15-server-clang-devel
kernel5.15-source
latex-mk
make-doc
perl-CPAN
policycoreutils-devel
sendmail-cf
spamassassin-sa-compile
task-c-devel
task-devel
x11-util-modular`

`[tpg@omv-rockpro64 mdv-next]$ dnf5 repoquery -q --latest-limit=1 --qf %{NAME} --whatrequires make
%{NAME}`

2. No new lines in dnf5 output - notice %{name} in argument is in lowercase to make it work

`[tpg@omv-rockpro64 mdv-next]$ dnf5 repoquery -q --latest-limit=1 --qf %{name} --whatrequires make
basesystem-builddkmsfontpackages-toolskernel-desktop-develkernel-rc-desktop-develkernel-rc-server-develkernel-rc-sourcekernel-server-develkernel-sourcekernel5.15-server-clang-develkernel5.15-sourcelatex-mkmake-docperl-CPANpolicycoreutils-develsendmail-cfspamassassin-sa-compiletask-c-develtask-develx11-util-modular`

**Comment by ppisar** [comment]
The unrecognized queryformat tag is because DNF5 moved to lower-case spelling. Contrary, RPM and DNF4 disregards a case. I agree that it's a bug which hinder a compatibility.

The missing new lines are tracked in issue #709. Please follow that issue for that matter. I will narrow your report to the letter case problem.

Until it is fixed, you can format your DNF5 query like this:

~~~
$ dnf5 repoquery -q --latest-limit=1 --qf '%{name}\n' --whatrequires make
~~~
